module.exports = {
  apps: [
    {
      name: "linode-pwa",
      script: "npm",
      args: "run preview",
      cwd: "/home/lincon/lincon",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        PORT: 18080,
        MONITOR_PORT: 3002,
      },
      log_file: "/home/lincon/logs/pm2-linode-pwa.log",
      out_file: "/home/lincon/logs/pm2-linode-pwa-out.log",
      error_file: "/home/lincon/logs/pm2-linode-pwa-error.log",
      time: true,
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 3000,
      listen_timeout: 8000,
      health_check_http: "http://localhost:18080/",
      health_check_grace_period: 10000,
    },
    {
      name: "system-monitor",
      script: "server/system-monitor.js",
      cwd: "/home/lincon/lincon",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "100M",
      env: {
        NODE_ENV: "production",
        MONITOR_PORT: 3002,
      },
      log_file: "/home/lincon/logs/pm2-system-monitor.log",
      out_file: "/home/lincon/logs/pm2-system-monitor-out.log",
      error_file: "/home/lincon/logs/pm2-system-monitor-error.log",
      time: true,
      restart_delay: 3000,
      max_restarts: 5,
      min_uptime: "5s",
      kill_timeout: 2000,
    },
  ],
};
